name: Feature Request
title: "[FR] - [Short description of the request]"
description: Suggest a new feature.
type: "Feature"
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of the feature you are requesting.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the motivation for the feature?
      description: Why would this feature be useful? What problem does it solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives have you considered?
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.